### ISSUE TITLE
Nerinyan API: Random beatmap

### ISSUE THREAD

**Issue by nyakokitsu** [Nerinyan/Nerinyan-WEB#41]
Query param in search

**Comment by zeee2** [comment]
You mean you want to an endpoint that returns randomizes a list of beatmaps?

**Comment by nyakokitsu** [comment]
> You mean you want to an endpoint that returns randomizes a list of beatmaps?

No, just one bmset

**Comment by zeee2** [comment]
well, that doesnt seems like a useful feature
